import os

# Base directory
BASE_DIR = os.path.abspath(os.path.dirname(__file__))

# Paths for data and subdirectories
DATA_DIR = os.path.join(BASE_DIR, "physionet.org", "files", "mimic-cxr", "2.1.0")
P10_DIR = os.path.join(DATA_DIR, "files", "p10")

# Metadata files
RECORD_FILE = os.path.join(DATA_DIR, "cxr-record-list.csv")
STUDY_FILE = os.path.join(DATA_DIR, "cxr-study-list.csv")

# Dataset paths
DATASET_DIR = os.path.join(BASE_DIR, "dataset")
TRAIN_DIR = os.path.join(DATASET_DIR, "train")
VALIDATION_DIR = os.path.join(DATASET_DIR, "validation")
TEST_DIR = os.path.join(DATASET_DIR, "test")

# Features directory (Extracted CNN features)
FEATURES_DIR = os.path.join(DATASET_DIR, "features")
FEATURES_TRAIN_DIR = os.path.join(FEATURES_DIR, "train")
FEATURES_VALIDATION_DIR = os.path.join(FEATURES_DIR, "validation")
FEATURES_TEST_DIR = os.path.join(FEATURES_DIR, "test")

# Reports directory (Tokenized reports)
REPORTS_TRAIN_DIR = os.path.join(DATASET_DIR, "train")
REPORTS_VALIDATION_DIR = os.path.join(DATASET_DIR, "validation")
REPORTS_TEST_DIR = os.path.join(DATASET_DIR, "test")

# Output paths
OUTPUT_DIR = os.path.join(BASE_DIR, "outputs")
MODELS_DIR = os.path.join(OUTPUT_DIR, "models")
REPORTS_DIR = os.path.join(OUTPUT_DIR, "reports")
LOGS_DIR = os.path.join(OUTPUT_DIR, "logs")

# Mappings directory
MAPPING_DIR = os.path.join(OUTPUT_DIR, "mappings")

# Medical abbreviations dictionary
MEDICAL_ABBREVIATIONS = {
    "//": "and",
    "a&e": "accident and emergency",
    "ab": "abdominal",
    "abn": "abnormality",
    "abx": "antibiotics",
    "aca": "anterior cerebral artery",
    "a.c.": "before meals",
    "af": "atrial fibrillation",
    "afib": "atrial fibrillation", 
    "a.m.": "morning",
    "am": "morning",
    "amhp": "approved mental health professional",
    "aml": "acute myeloid leukemia",
    "ant": "anterior",
    "ao": "aorta",
    "aoc": "aortic coarctation",
    "ap": "anteroposterior",
    "aptt": "activated partial thromboplastin time",
    "asa": "aspirin",
    "asc": "ascending",
    "asq": "ages and stages questionnaire",
    "atx": "antibiotic therapy",
    "av": "aortic valve",
    "a/v": "aortic value",
    "avm": "arteriovenous malformation",
    "avr": "aortic valve replacement",
    "bb": "ball bearing",
    "b.d.s": "2 times a day",
    "bds": "2 times a day",
    "b.i.d.": "twice a day",
    "bid": "twice a day",
    "biv": "biventricular",
    "bd": "twice a day",
    "bl": "bilateral",
    "bmi": "body mass index",
    "bms": "bare metal stent",
    "bmt": "bone marrow transplant",
    "bno": "bowels not open",
    "bnp": "b type natriuretic peptide",
    "bo": "bowels open",
    "bp": "blood pressure",
    "bs": "breath sounds",
    "bx": "biopsy",
    "ca": "cancer",
    "cad": "coronary artery disease",
    "cb": "coronary branch",
    "c/b": "complicated by",
    "cca": "common carotid artery",
    "ccu": "coronary care unit",
    "ccy": "cholecystectomy",
    "cd": "crohn's disease",
    "c/f": "concern for",
    "c/o": "complaints of",
    "chf": "congestive heart failure",
    "ckd": "chronic kidney disease",
    "cll": "chronic lymphocytic leukemia",
    "cmhn": "community mental health nurse",
    "cml": "chronic myelogenous leukemia ",
    "cns": "central nervous system",
    "co2": "carbon dioxide",
    "cop": "cryptogenic organizing pneumonia",
    "copd": "chronic obstructive pulmonary disease",
    "cp": "catamenial pneumothorax",
    "cpn": "community psychiatric nurse",
    "csf": "cerebrospinal fluid",
    "csu": "catheter stream urine sample",
    "ct": "computerised tomography scan",
    "ct.": "computerised tomography scan",
    "ct scan": "computerised tomography scan",
    "cta": "computed tomography angiography",
    "cva": "cerebral vascular accident",
    "cvc": "central venous catheter",
    "cvl": "central venous line",
    "cvp": "central venous pressure",
    "c/w": "consistent with",
    "cxr": "chest x ray",
    "dchf": "decompensated congestive heart failure",
    "d/c": "discharge",
    "de": "decompensated",
    "dep": "dependent",
    "des": "drug eluting stent",
    "dm": "diabetes mellitus",
    "dmii": "type 2 diabetes mellitus",
    "dnacpr": "do not attempt cardiopulmonary resuscitation",
    "dnar": "do not attempt resuscitation",
    "dnr": "do not resuscitate",
    "doe": "dyspnea on exertion",
    "dr": "doctor",
    "dr.": "doctor",
    "dvt": "deep vein thrombosis",
    "dw": "discussed with",
    "d/w": "discussed with",
    "dx": "digital x ray",
    "dz": "disease",
    "ecg": "electrocardiogram",
    "ed": "emergency department",
    "eeg": "electroencephalogram",
    "ef": "ejection fraction",
    "eff": "pleural effusions",
    "egd": "esophagogastroduodenoscopy",
    "ekg": "electrocardiogram",
    "emu": "early morning urine sample",
    "esr": "erythrocyte sedimentation rate",
    "et": "endotracheal",
    "ett": "endotracheal tube",
    "eo": "evidence of",
    "e/o": "evidence of",
    "eua": "examination under anaesthetic",
    "eval": "evaluate",
    "exp": "exploratory",
    "f": "woman",
    "fas": "fasciitis",
    "fasc": "fasciitis",
    "fbc": "full blood count",
    "fdg": "fluorodeoxyglucose",
    "fobt": "faecal occult blood test",
    "fib": "fibrillation",
    "fit": "faecal immunochemical test",
    "ftt": "failure to thrive",
    "fup": "follow up",
    "f/u": "follow up",
    "fy1": "foundation doctor",
    "fy2": "foundation doctor",
    "fx": "fracture",
    "g": "gastronomy",
    "ga": "general anaesthetic",
    "ge": "gastroesophageal",
    "gib": "gastrointestinal bleed",
    "gj": "gastrojejunostomy",
    "goo": "gastric outlet obstruction",
    "gnr": "gram negative rod",
    "gtt.": "drop(s)",
    "gtt": "drop(s)",
    "h.": "hour",
    "h": "hour",
    "hcc": "hepatocellular carcinoma",
    "hct": "hematocrit",
    "hep": "hepatitis",
    "hf": "heart failure",
    "ho": "history of",
    "hb": "haemoglobin",
    "hca": "healthcare assistant",
    "hcsw": "healthcare support worker",
    "hd": "hemodialysis",
    "hdl": "high density lipoprotein",
    "h/h": "hemoglobin and hematocrit",
    "hiv": "human immunodeficiency virus",
    "hld":"hyperlipidemia",
    "hrt": "hormone replacement therapy",
    "ht": "height",
    "htn": "hypertension",
    "hx": "history",
    "i": "1 tablet",
    "iabp": "intra aortic balloon pump",
    "ica": "internal carotid artery",
    "icd": "implantable cardioverter defibrillator",
    "icp": "intracranial pressure",
    "icu": "intensive care unit",
    "ii": "2 tablets",
    "ij": "internal juglar",
    "iii": "3 tablets",
    "ild": "interstitial lung disease",
    "ili": "influenza like illness",
    "i.m.": "injection into a muscle",
    "im": "injection into a muscle",
    "inc": "increased",
    "ip": "interventional procedures",
    "iph": "intracranial hemorrhage",
    "ir": "interventional radiology",
    "i.v.": "injection directly to a vein",
    "iv": "injection directly to a vein",
    "iv.": "intravenous",
    "ivc": "inferior vena cava",
    "ivh": "intraventricular hemorrhage",
    "ini": "interval",
    "inr": "international normalised ratio",
    "ivi": "intravenous infusion",
    "ivp": "intravenous pyelogram",
    "ix": "investigations",
    "j": "jejunostomy",
    "jp": "jackson pratt",
    "kub": "kidney ureter and bladder",
    "l": "left",
    "la": "local anaesthetic",
    "lad": "left anterior descending",
    "lap": "laparotomy",
    "lar": "lower anterior resection",
    "lat":"lateral view",
    "ldl": "low density lipoprotein",
    "lft": "liver function test",
    "lij": "left internal jugular",
    "ll": "lower lobe",
    "lle": "left lower extremity",
    "lll": "left lower lobe",
    "llq": "left lower quadrant",
    "lmp": "last menstrual period",
    "loa": "loss of appetite",
    "loc": "loss of consciousness",
    "lr": "left and right",
    "lul": "left upper lobe",
    "ls": "left sided",
    "lt": "left sided",
    "lv": "left ventricle",
    "lvh": "left ventricle hypertrophy",
    "m": "man",
    "mca": "middle cerebral artery",
    "mcc": "motorcyle crash",
    "mcp": "metacarpophalangeal",
    "md": "patients doctor",
    "mie": "minimally invasive esophagectomy",
    "mk": "mild",
    "mri": "magnetic resonance imaging",
    "mrsa": "methicillin-resistant staphylococcus aureus",
    "mod": "moderate",
    "msu": "mid-stream urine sample",
    "mv": "mitral valve",
    "mvr": "mitral valve replacement",
    "mva": "motor vehicle accident",
    "mvc": "motor vehicle collision",
    "ngt": "nasogastric tube",
    "n.p.o.": "nothing by mouth",
    "npo": "nothing by mouth",
    "nad": "nothing abnormal discovered",
    "nai": "non accidental injury",
    "nbm": "nil by mouth",
    "nec": "necrotising",
    "neg": "negative",
    "ng": "nasogastric",
    "nocte": "every night",
    "nof": "neck of femur",
    "nsr": "normal sinus rhythm",
    "nsaid": "non steroidal anti inflammatory drug",
    "nstemi": "non st elevation myocardial infarction",
    "n/v": "nausea and vomiting",
    "oa": "osteoarthritis",
    "o.d.": "once a day",
    "od": "once a day",
    "o/e": "on examination",
    "ot": "occupational therapist",
    "pa":"posterior anterior",
    "pacu": "post anesthesia care unit",
    "pafib": "paroxysmal atrial fibrillation",
    "pci": "percutaneous coronary intervention",
    "p.c.": "after food",
    "pdt": "productive",
    "pe": "pulmonary embolism",
    "peg": "percutaneous endoscopic gastrostomy",
    "picc": "peripherally inserted central catheters",
    "plcmt": "placement",
    "pls": "primary lateral sclerosis",
    "p.m.": "afternoon or evening",
    "pm": "afternoon or evening",
    "pmh": "past medical history",
    "pna":"pneumonia",
    "p.o.": "orally",
    "po": "orally",
    "pod": "post-operative",
    "ppd": "purified protein derivative",
    "p.r.": "rectally",
    "pr": "rectally",
    "p.r.n.": "as needed",
    "prn": "as needed",
    "p/c": "presenting complaint",
    "p/w": "presenting with",
    "pt": "patient",
    "pta": "prior to admission",
    "ptx": "pneumothorax",
    "pop": "plaster of paris",
    "ptt": "partial thromboplastin time",
    "pu": "passed urine",
    "q.": "every",
    "q.1.d.": "every day",
    "q1d": "every day",
    "q.1.h.": "every hour",
    "q1h": "every hour",
    "q.2.h.": "every 2 hours",
    "q2h": "every 2 hours",
    "q.4.h.": "every 4 hours",
    "q4h": "every 4 hours",
    "q.6.h.": "every 6 hours",
    "q6h": "every 6 hours",
    "q.8.h.": "every 8 hours",
    "q8h": "every 8 hours",
    "q.d.": "every day",
    "qd": "every day",
    "q.d.s": "4 times a day",
    "qds": "4 times a day",
    "q.h.": "every hour",
    "qh": "every hour",
    "q.i.d": "4 times a day",
    "qid": "4 times a day",
    "q.o.d.": "every other day",
    "qod": "every other day",
    "q.s.": "a sufficient quantity",
    "qs": "a sufficient quantity",
    "rle": "right lower extremity",
    "rll": "right lower lobe",
    "rn": "registered nurse",
    "rnld": "learning disability nurse",
    "r/o": "rule out",
    "rosc": "return of spontaneous circulation",
    "rm": "right middle",
    "rr": "respitory rate",
    "rsv": "respiratory syncytial virus",
    "rta": "road traffic accident",
    "rtx": "radiation therapy",
    "ru": "right upper",
    "ruq": "right upper quadrant",
    "rx": "treatment",
    "rvr": "rapid ventricular response",
    "sah": "subarachnoid hemorrhage",
    "sao2": "oxygen saturation",
    "sat": "saturation",
    "sdh": "subdural hemorrhage",
    "s.c.": "injection under the skin",
    "sc": "injection under the skin",
    "s/p": "status post",
    "sr": "sustained release",
    "sss": "sick sinus syndrome",
    "sob": "shortness of breath",
    "spr": "specialist registrar",
    "stat.": "immediately",
    "stemi": "st-segment elevation myocardial infarction",
    "svc": "superior vena cava",
    "svt": "supraventricular tachycardia",
    "sxs": "symptons",
    "tb": "tuberculosis",
    "tbi": "traumatic brain injury",
    "t.d.s": "3 times a day",
    "tds": "3 times a day",
    "t.i.d.": "3 times a day",
    "tid": "3 times a day",
    "tci": "to come in",
    "tfn": "trochanteric femoral nailing",
    "tft": "thyroid function test",
    "tpn": "total parenteral nutrition",
    "tpr": "temperature, pulse and respiration",
    "tr": "tricuspid regurgitation",
    "tta": "to take away",
    "tto": "to take out",
    "txf": "transfer",
    "u&e": "urea and electrolytes",
    "u.d.": "as directed",
    "ud": "as directed",
    "ucc": "urgent care centre",
    "us": "ultrasound",
    "u/s": "ultrasound",
    "uti": "urinary tract infection",
    "vats": "video assisted thoracoscopic surgery",
    "vldl": "very-low density lipoprotein",
    "vs.": "versus",
    "vw": "view",
    "vte": "venous thromboembolism",
    "wbc": "white blood cells",
    "w.": "with",
    "ws": "water seal",
    "wt": "weight",
    "xr": "x ray",
    "yo": "year old"
}